name: snake_player_flutter_example
description: Demonstrates how to use the snake_player_flutter plugin.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  snake_player_flutter:
#    path: ../
  snake_player_flutter: ^0.0.6 #https://pub.dev/packages/snake_player_flutter

  cupertino_icons: ^1.0.2
  #connectivity_plus: ^1.0.2 #https://pub.dev/packages/connectivity_plus
  #event_bus: ^2.0.0 #https://pub.dev/packages/event_bus
  #focus_detector: ^2.0.0 #https://pub.dev/packages/focus_detector
  url_launcher: ^6.0.15 #https://pub.dev/packages/url_launcher
  logger: ^1.0.0 #https://pub.dev/packages/logger
  get: ^4.1.4 #https://pub.dev/packages/get
  #rxdart: ^0.27.1 #https://pub.dev/packages/rxdart
  in_app_review: ^2.0.2 #https://pub.dev/packages/in_app_review
  #package_info_plus: ^1.0.2 #https://pub.dev/packages/package_info_plus
  #path_provider: ^2.0.2 #https://pub.dev/packages/path_provider
  #http: ^0.13.3 #https://pub.dev/packages/http

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
#    - assets/videos/
#    - assets/images/
