name: snake_player_flutter_example
description: Demonstrates how to use the snake_player_flutter plugin.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  snake_player_flutter:
#    path: ../
  snake_player_flutter: ^0.0.6 #https://pub.dev/packages/snake_player_flutter

  cupertino_icons: ^1.0.4 #https://pub.dev/packages/cupertino_icons
  url_launcher: ^6.0.20 #https://pub.dev/packages/url_launcher
  logger: ^1.1.0 #https://pub.dev/packages/logger
  get: ^4.6.1 #https://pub.dev/packages/get
  in_app_review: ^2.0.4 #https://pub.dev/packages/in_app_review

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
#    - assets/videos/
#    - assets/images/
