name: hello_word
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  #connectivity_plus: ^1.0.2 #https://pub.dev/packages/connectivity_plus
  #event_bus: ^2.0.0 #https://pub.dev/packages/event_bus
  #focus_detector: ^2.0.0 #https://pub.dev/packages/focus_detector
  url_launcher: ^6.0.3 #https://pub.dev/packages/url_launcher
  logger: ^1.0.0 #https://pub.dev/packages/logger
  get: ^4.1.4 #https://pub.dev/packages/get
  #rxdart: ^0.27.1 #https://pub.dev/packages/rxdart
  in_app_review: ^2.0.2 #https://pub.dev/packages/in_app_review
  #package_info_plus: ^1.0.2 #https://pub.dev/packages/package_info_plus
  path_provider: ^2.0.2 #https://pub.dev/packages/path_provider
  #http: ^0.13.3 #https://pub.dev/packages/http

  better_player: ^0.0.74 #https://pub.dev/packages/better_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2" #https://pub.dev/packages/flutter_launcher_icons
  #flutter_native_splash: ^1.2.3 #https://pub.dev/packages/flutter_native_splash
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: data_repo/fonts/Pacifico-Regular.ttf
          weight: 400

  assets:
    - assets/
#    - assets/videos/
#    - assets/images/
