name: hello_word
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.8+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #null safety
  advance_pdf_viewer: ^2.0.0 #https://pub.dev/packages/advance_pdf_viewer
  animated_background: ^2.0.0 #https://pub.dev/packages/animated_background
  animated_text_kit: ^4.2.1 #https://pub.dev/packages/animated_text_kit
  avatar_glow: ^2.0.1 #https://pub.dev/packages/avatar_glow
  battery_plus: ^1.0.1 #https://pub.dev/packages/battery_plus
  blur: ^3.0.0 #https://pub.dev/packages/blur
  connectivity_plus: ^1.0.2 #https://pub.dev/packages/connectivity_plus
  country_picker: ^2.0.5 #https://pub.dev/packages/country_picker
  cupertino_icons: ^1.0.3
  drag_select_grid_view: ^0.5.1 #https://pub.dev/packages/drag_select_grid_view
  device_info_plus: ^1.0.1 #https://pub.dev/packages/device_info_plus
  delayed_display: ^2.0.0 #https://pub.dev/packages/delayed_display
  dio: ^4.0.0-beta6 #https://pub.dev/packages/dio
  dotted_border: ^2.0.0 #https://pub.dev/packages/dotted_border
  draggable_scrollbar: ^0.1.0 #https://pub.dev/packages/draggable_scrollbar
  english_words: ^4.0.0 #https://pub.dev/packages/english_words
  event_bus: ^2.0.0 #https://pub.dev/packages/event_bus
  easy_debounce: ^2.0.0 #https://pub.dev/packages/easy_debounce
  focus_detector: ^2.0.0 #https://pub.dev/packages/focus_detector
  fl_chart: ^0.36.1 #https://pub.dev/packages/fl_chart
  flutter_easyloading: ^3.0.0 #https://pub.dev/packages/flutter_easyloading
  flutter_local_notifications: ^5.0.0+4 #https://pub.dev/packages/flutter_local_notifications
  flutter_reaction_button: ^1.0.8 #https://pub.dev/packages/flutter_reaction_button
  flutter_slidable: ^0.6.0 #https://pub.dev/packages/flutter_slidable
  flutter_staggered_grid_view: ^0.4.0 #https://pub.dev/packages/flutter_staggered_grid_view
  flutter_svg: ^0.22.0 #https://pub.dev/packages/flutter_svg
  flutter_speed_dial: ^3.0.5 #https://pub.dev/packages/flutter_speed_dial
  flutter_sticky_header: ^0.6.0 #https://pub.dev/packages/flutter_sticky_header
  overflow_view: ^0.3.1 #https://pub.dev/packages/overflow_view
  transparent_image: ^2.0.0 #https://pub.dev/packages/transparent_image
  sqflite: ^2.0.0+3 #https://pub.dev/packages/sqflite
  url_launcher: ^6.0.3 #https://pub.dev/packages/url_launcher
  share_plus: ^2.1.4 #https://pub.dev/packages/share_plus
  simple_url_preview: ^3.0.1 #https://pub.dev/packages/simple_url_preview
  shimmer: ^2.0.0 #https://pub.dev/packages/shimmer
  marquee: ^2.1.0 #https://pub.dev/packages/marquee
  logger: ^1.0.0 #https://pub.dev/packages/logger
  lazy_load_scrollview: ^1.3.0 #https://pub.dev/packages/lazy_load_scrollview
  like_button: ^2.0.2 #https://pub.dev/packages/like_button
  network_info_plus: ^1.1.0 #https://pub.dev/packages/network_info_plus
  get: ^4.1.4 #https://pub.dev/packages/get
  rxdart: ^0.27.1 #https://pub.dev/packages/rxdart
  #imageview360: ^1.2.0 #https://pub.dev/packages/imageview360
  image_picker: ^0.8.1+1 #https://pub.dev/packages/image_picker
  intl: ^0.17.0 #https://pub.dev/packages/intl
  horizontal_data_table: ^3.3.0 #https://pub.dev/packages/horizontal_data_table
  video_player: ^2.1.5 #https://pub.dev/packages/video_player
  image_gallery_saver: ^1.6.9 #https://pub.dev/packages/image_gallery_saver
  in_app_review: ^2.0.2 #https://pub.dev/packages/in_app_review
  photo_view: ^0.12.0 #https://pub.dev/packages/photo_view
  package_info_plus: ^1.0.2 #https://pub.dev/packages/package_info_plus
  permission_handler: ^6.0.1 #https://pub.dev/packages/permission_handler
  pin_code_fields: ^7.2.0 #https://pub.dev/packages/pin_code_fields
  progress_state_button: ^1.0.3 #https://pub.dev/packages/progress_state_button
  tiengviet: ^0.5.0 #https://pub.dev/packages/tiengviet
  timeago: ^3.1.0 #https://pub.dev/packages/timeago
  wave: ^0.2.0 #https://pub.dev/packages/wave
  webview_flutter: ^2.0.6 #https://pub.dev/packages/webview_flutter
  web_scraper: ^0.1.4 #https://pub.dev/packages/web_scraper

  #scoped_model: ^1.1.0 #https://pub.dev/packages/scoped_model
  #table_calendar: ^3.0.0 #https://pub.dev/packages/table_calendar
  cached_network_image: ^3.1.0 #https://pub.dev/packages/cached_network_image
  path_provider: ^2.0.3 #https://pub.dev/packages/path_provider
  http: ^0.13.3 #https://pub.dev/packages/http
  basic_utils: ^3.6.0 #https://pub.dev/packages/basic_utils
  encrypt: ^5.0.1 #https://pub.dev/packages/encrypt
  crypto: ^3.0.1 #https://pub.dev/packages/crypto/install
  flutter_native_splash: ^1.2.3 #https://pub.dev/packages/flutter_native_splash
  shared_preferences: ^2.0.7 #https://pub.dev/packages/shared_preferences
  restart_app: ^1.0.3 #https://pub.dev/packages/restart_app

  #none null safety
  #flutter_swiper: ^1.1.6 #https://pub.dev/packages/flutter_swiper
  #md2_tab_indicator: ^1.0.2 #https://pub.dev/packages/md2_tab_indicator
  #drag_to_expand: ^0.0.1 #https://pub.dev/packages/drag_to_expand
  #kenburns: ^1.0.5 #https://pub.dev/packages/kenburns

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2" #https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.jpg"
#  flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: data_repo/fonts/Pacifico-Regular.ttf
          weight: 400

  assets:
    #    - assets/
    - assets/videos/
    - assets/images/
    - assets/pdf/
    - assets/sample/
    - data_repo/starwars_data.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
