name: snake_player_flutter
description: Simple Streaming at scale.
  Uiza is the complete toolkit for building a powerful video streaming application with unlimited scalability. We design Uiza so simple that you only need a few lines of codes to start streaming, but sophisticated enough for you to build complex products on top of it.
version: 0.0.5
homepage: https://github.com/uizaio/snake.sdk.flutter-player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  better_player: ^0.0.79 #https://pub.dev/packages/better_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.uiza.snake_player_flutter
        pluginClass: SnakePlayerFlutterPlugin
      ios:
        pluginClass: SnakePlayerFlutterPlugin
