name: snake_player_flutter
description: A new flutter plugin project.
version: 0.0.2
homepage: https://github.com/uizaio/snake.sdk.flutter-player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  better_player: ^0.0.76 #https://pub.dev/packages/better_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.uiza.snake_player_flutter
        pluginClass: SnakePlayerFlutterPlugin
      ios:
        pluginClass: SnakePlayerFlutterPlugin
